import MaxWidthWrapper from "../max-width-wrapper"
import LargeBlueStar from '../../assets/img/stars/large-blue-star.svg';
import { FaCheckSquare } from "react-icons/fa";
import { ImArrowRight } from "react-icons/im";

const PContentSection = () => {
  return (
    <div className="py-16">
    <MaxWidthWrapper>
      <div className="w-full lg:w-[80%] justify-self-center border border-red-600 px-2">
          <div className="font-myFont text-myBlack text-lg/8 md:text-xl/10">

            <p className="mt-6">Last updated: September 19, 2024</p>
            <p className="">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className="">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>

            <p className="mt-10 font-bold text-center text-lg/8 md:text-3xl/10">Interpretation and Definitions</p>
            <p className="mt-10 font-bold">Interpretation</p>
            <p className="mt-6">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <p className="mt-6 font-bold">Definitions</p>
            <p className="mt-6 font-bold">For the purposes of this Privacy Policy:</p>
            <ul className="font-bold list-disc list-inside lis">
              <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
              <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Lenob Private Limited Company, Nic Lums Pakistan.</li>
              <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li>Country refers to: Pakistan</li>
              <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
              <li>Service refers to the Website.</li>
              <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
              <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li>Website refers to lenob, accessible from lenob.co</li>
              <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <p className="mt-10 font-bold text-center text-lg/8 md:text-3xl/10">Collecting and Using Your Personal Data</p>
            <p className="mt-10 font-bold">Types of Data Collected</p>
            <p className="mt-6 font-bold">Personal Data</p>
            <p className="mt-6">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc list-inside">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>
            <p className="mt-6 font-bold">Usage Data</p>
            <p className="mt-6">Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <p className="mt-6 font-bold">Information from Third-Party Social Media Services</p>
            <p className="mt-6">The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
            <ul className="list-disc list-inside">
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>
            <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
            <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
            <p className="mt-6 font-bold">Tracking Technologies and Cookies</p>
            <p className="mt-6">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul className="list-disc list-inside">
              <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
              <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.</p>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul className="list-disc list-inside mt-6">
              <li>Necessary / Essential Cookies</li>
              <li>Type: Session Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
              <li>Cookies Policy / Notice Acceptance Cookies</li>
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
              <li>Functionality Cookies</li>
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
            </ul>
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

            {[
              { text: "Ad budgets drained with nothing to show for it." },
              { text: "Engagement that never translates to sales." },
              { text: "Generic campaigns lost in the noise." },
            ].map((item, index) => (
              <div key={index} className="flex items-start gap-2">
                <FaCheckSquare className="size-7 md:size-8 fill-myDarkPrimary flex-shrink-0" />
                <p>{item.text}</p>
              </div>
            ))}
            <p className="mt-10">That's where we come in.</p>
            <p>We specialize in turning “likes” into loyal customers, “shares” into sales, and clicks into consistent revenue.</p>
            <p className="mt-10">One of our recent campaigns achieved:</p>
            {[
              { text: "8,000+ clicks" },
              { text: "1,400+ conversions" },
              { text: "$120,000 in Revenue" },
            ].map((item, index) => (
              <div key={index} className="flex items-start gap-2">
                <ImArrowRight className="size-7 md:size-8 fill-myPrimary flex-shrink-0" />
                <p>{item.text}</p>
              </div>
            ))}
          </div>            
      </div>
      </MaxWidthWrapper>
    </div>
  )
}

export default PContentSection